<center style="font-size:35px;color:red;font-weight:bold"> Initiation à Python</center><br>
<center style="color:black;font-size:20px"> Programmation Scientifique  </center>
<center style="color:black;font-size:14px"> NumPy </center>
<br>
<center style="color:black">**Cours du Pr. Abdellah AZMANI**</center>
<center style="color:black">**Département Génie Informatique**</center>
<br>
<center style="color:black">Université Abdelmalek Essaadi</center>
<center style="color:black">Faculté des Sciences et Techniques</center>
<center style="color:black">Tanger</center>

## NumPy
### Qu'est-ce que NumPy?
   * NumPy est une bibliothèque Python utilisée pour travailler avec des tableaux.
   * Il a également des fonctions pour travailler dans le domaine de l'algèbre linéaire, de la transformée de Fourier et des matrices.
   * NumPy a été créé en 2005 par Travis Oliphant. C'est un projet open source et vous pouvez l'utiliser librement.

**NumPy signifie Numerical Python.**

### Pourquoi utiliser NumPy?
En Python, nous avons des listes qui servent à des tableaux, mais elles sont lentes à traiter.<br>
NumPy vise à fournir un objet de tableau jusqu'à 50 fois plus rapide que les listes Python traditionnelles.<br>
L'objet tableau dans NumPy s'appelle ndarray, il fournit de nombreuses fonctions de support qui facilitent le travail avec ndarray.<br>
Les tableaux sont très fréquemment utilisés dans la science des données, où la vitesse et les ressources sont très importantes.<br>

### Pourquoi NumPy est-il plus rapide que les listes?
Les tableaux NumPy sont stockés à un endroit continu de la mémoire contrairement aux listes, de sorte que les processus peuvent y accéder et les manipuler très efficacement.<br>
Ce comportement est appelé localité de référence en informatique.<br>
C'est la raison principale pour laquelle NumPy est plus rapide que les listes. Il est également optimisé pour fonctionner avec les dernières architectures CPU.

### Dans quelle langue NumPy est-il écrit?
NumPy est une bibliothèque Python et est écrite partiellement en Python, mais la plupart des parties qui nécessitent un calcul rapide sont écrites en C ou C ++.

### Où se trouve la base de code NumPy?
Le code source de NumPy se trouve dans ce référentiel github https://github.com/numpy/numpy

### Importation NumPy
Pour utiliser la bibliothèque Numpy, il faut utiliser le mots clé import à l’entête de notre programme suivie de nom de la bibliothèque qu’est dans notre cas « Numpy ».<br>
Exemple : 

In [2]:
import numpy

In [4]:
import numpy 
arr = numpy.array([1, 2, 3, 4, 5]) 
print(arr)

[1 2 3 4 5]


### Alias
Pour augmenter la productivité des programmeurs en python, on utilise souvent le mots clé « as » après l’importation de la bibliothèque pour renommer la bibliothèque par un nom moins difficile à apprendre et facile à écrire.

In [5]:
import numpy as np

In [6]:
import numpy as np 
arr = np.array([1, 2, 3, 4, 5]) 
print(arr)

[1 2 3 4 5]


### Création d’un tableau 
Pour créer un tableau, on utilise la fonction numpy.array(). On utilise des crochets pour délimiter les listes d’éléments dans les tableaux.<br>
Exemple :

In [2]:
import numpy as np 
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [3]:
print(type(arr))

<class 'numpy.ndarray'>


## Dimensions dans les tableaux
la dimension dans les tableaux est le niveau de profondeur de tableau (tableaux imbriqués).
#### Tableaux 0D
Les tableaux 0D, ou scalaires, sont les éléments d'un tableau. Chaque valeur d'un tableau est un tableau 0D.

In [11]:
import numpy as np
arr = np.array(42)
print(arr)

42


#### Tableaux 1D
Un tableau qui a des tableaux 0D comme éléments est appelé tableau unidimensionnel ou 1D.<br>
Ce sont les tableaux les plus courants et les plus basiques.

In [13]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


#### Matrices 2D
Un tableau qui a des tableaux 1D comme éléments est appelé un tableau 2D.<br>
Ceux-ci sont souvent utilisés pour représenter des matrices ou des tenseurs de second ordre.

In [14]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


#### Matrices 3D
Un tableau qui a des tableaux 2D (matrices) comme éléments est appelé tableau 3D.<br>
Ceux-ci sont souvent utilisés pour représenter un tenseur du 3ème ordre.

In [15]:
import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


**Pour vérifier la dimensions, NumPy Arrays fournit l'attribut ndim qui renvoie un entier qui nous indique le nombre de dimensions du tableau.**

In [16]:
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim) 
print(b.ndim) 
print(c.ndim) 
print(d.ndim)

0
1
2
3


## Accéder aux éléments d'un tableau
L'indexation de tableau équivaut à accéder à un élément de tableau.<br>
Vous pouvez accéder à un élément de tableau en vous référant à son numéro d'index.<br>
Les index des tableaux **NumPy** commencent par 0, ce qui signifie que le premier élément a l'index 0 et le second l'index 1, etc.

In [17]:
import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr[0])

1


In [19]:
import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr[2] + arr[3]) # Récupérez les troisième et quatrième éléments du tableau et afficher leur somme.

7


### Accès aux éléments d'un tableau 2D
Pour accéder aux éléments des tableaux 2D, nous pouvons utiliser des entiers séparés par des virgules représentant la dimension et l'index de l'élément.

In [20]:
# Accédez au 2ème élément du premier tableau :
import numpy as np
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('2ème élément du premier tableau: ', arr[0, 1])

2ème élément du premier tableau:  2


In [21]:
# Accédez au 5ème élément du deuxième tableau
import numpy as np
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('5ème élément du deuxième tableau: ', arr[1, 4])

5ème élément du deuxième tableau:  10


### Accés aux éléments d'un tableau 3D
Pour accéder aux éléments des tableaux 3D, nous pouvons utiliser des entiers séparés par des virgules représentant les dimensions et l'index de l'élément.

In [22]:
# Accédez au troisième élément du deuxième tableau du premier tableau:
import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[0, 1, 2])

6


#### Explication :
arr [0, 1, 2] imprime la valeur 6.

Le premier nombre représente la première dimension, qui contient deux tableaux:
**[[1, 2, 3], [4, 5, 6]]**
et:
**[[7, 8, 9], [10, 11, 12]]**
Puisque nous avons sélectionné 0, nous nous retrouvons avec le premier tableau:
[[1, 2, 3], [4, 5, 6]]

Le deuxième nombre représente la deuxième dimension, qui contient également deux tableaux:
**[1, 2, 3]**
et:
**[4, 5, 6]**
Puisque nous avons sélectionné 1, nous nous retrouvons avec le deuxième tableau:
**[4, 5, 6]**

Le troisième nombre représente la troisième dimension, qui contient trois valeurs:
**4
5
6**
Puisque nous avons sélectionné 2, nous nous retrouvons avec la troisième valeur:
6

## Indexation négative
Utilisez l'indexation négative pour accéder à un tableau depuis la fin.

In [24]:
# Imprimez le dernier élément du 2ème tableau:
import numpy as np
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('dernier élément du 2ème tableau: ', arr[1, -1])

dernier élément du 2ème tableau:  10


## Découpage de tableau
* Le découpage en python signifie prendre des éléments d'un index donné à un autre index donné.
* Nous passons slice au lieu d'index comme ceci: [start: end].
* Nous pouvons également définir l'étape, comme ceci: [start: end: step].

#### Exemple
Découpez les éléments de l'index 1 à l'index 5 dans le tableau suivant

In [8]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])

[2 3 4 5]


#### Exemple
Découpez les éléments de l'index 4 à la fin du tableau:

In [7]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[4:])

[5 6 7]


#### Exemple
Découpez les éléments du début à l'index 4 (non inclus):

In [6]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[:4])

[1 2 3 4]


## Tranchage négatif
Utilisez l'opérateur moins pour faire référence à un index à partir de la fin:
#### Exemple
Tranche de l'index 3 de la fin à l'index 1 de la fin:

In [9]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[-3:-1])

[5 6]


## STEP
Utilisez la valeur de l'étape pour déterminer l'étape du tranchage:

#### Exemple
Renvoie tous les autres éléments de l'index 1 à l'index 5:

In [10]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5:2])

[2 4]


#### Exemple
Renvoie tous les autres éléments du tableau entier:

In [11]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[::2])

[1 3 5 7]


### Tableau 2D
#### Exemple 1
À partir du deuxième élément, découpez les éléments de l'index 1 à l'index 4 (non inclus):

In [14]:
import numpy as np
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 1:4])

[7 8 9]


#### Exemple 2
À partir des deux éléments, renvoyez l'index 2:

In [15]:
import numpy as np
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2, 2])

[3 8]


#### Exemple 3
À partir des deux éléments, de l'index 1 à l'index 4 (non inclus), cela renverra un tableau 2D:

In [16]:
import numpy as np
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


## Types de données en Python
Par défaut, Python a ces types de données:

* strings - utilisées pour représenter des données textuelles, le texte est placé entre guillemets. par exemple. "A B C D"
* integer - utilisé pour représenter des nombres entiers. par exemple. -1, -2, -3
* float - utilisé pour représenter des nombres réels. par exemple. 1,2, 42,42
* booléen - utilisé pour représenter True ou False.
* complex - utilisé pour représenter un nombre complexe. par exemple. 1,0 + 2,0j, 1,5 + 2,5j

## Types de données NumPy
NumPy a quelques types de données supplémentaires et fait référence à des types de données avec un caractère, comme i pour les entiers, u pour les entiers non signés, etc.

Vous trouverez ci-dessous une liste de tous les types de données dans NumPy et les caractères utilisés pour les représenter.

| Caractère | Type de données | Description | Exemple |
| :-------- | :--------- | :--------- | :--------- |
| i | integer | Entier Signé | 128 |
| b | boolean | Booléen | True ou False |
| u | unsigned integer | Entier non signé | |
| f | float | Nombre à virgule flottante |14.5|
| c | complex float | Complexe | 2 + 3j|
| M | datetime | Date et heure | 2020-01-01 |
| O | object | Objet | Voiture |
| S | string | Chaîne de caractères | "Bonjour" |
| U | unicode string | Chaîne de caractère non signé | 0A |


## Vérification du type de données d'un tableau
L'objet tableau NumPy a une propriété appelée dtype qui renvoie le type de données du tableau:

| Type de données | Description |
| :--------- | :----------------------- |
| bool | Booléen |
| int8 | Entier signé 8 bits |
| int16 | Entier signé 16 bits |
| int32 | Entier signé 32 bits |
| int64 | Entier signé 64 bits |
| uint8 | Entier non signé 8 bits |
| uint16 | Entier non signé 16 bits |
| uint32 | Entier non signé 32 bits |
| uint64 | Entier non signé 64 bits |
| float16 | Nombre à virgule flottante 16 bitss |
| float32 | Nombre à virgule flottante 32 bits |
| float64 | Nombre à virgule flottante 64 bits |
| complex64 | Nombre complexe 64 bits |
| complex128 | Nombre complexe de 128 bits |

In [17]:
import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr.dtype)

int64


In [18]:
import numpy as np
arr = np.array(['apple', 'banana', 'cherry'])
print(arr.dtype)

<U6


## Création de tableaux avec un type de données défini
Nous utilisons la fonction array() pour créer des tableaux, cette fonction peut prendre un argument optionnel: **dtype** qui nous permet de définir le type de données attendu des éléments du tableau:

In [20]:
# Création d'un tableau avec une chaîne de caractère comme type de données:
import numpy as np
arr = np.array([1, 2, 3, 4], dtype='S')
print(arr)

[b'1' b'2' b'3' b'4']


In [21]:
print(arr.dtype)

|S1


**Pour i, u, f, S et U, nous pouvons également définir la taille.**

In [22]:
import numpy as np
arr = np.array([1, 2, 3, 4], dtype='i4')
print(arr)
print(arr.dtype)

[1 2 3 4]
int32


## Tableau NumPy : Copy vs View

La différence entre Copy et View : 
* La principale différence entre une Copy et View d'un tableau est que la copie est un nouveau tableau et que la vue n'est qu'une vue du tableau d'origine.

* La copie possède les données et les modifications apportées à la copie n'affecteront pas la matrice d'origine, et toutes les modifications apportées à la matrice d'origine n'affecteront pas la copie.

* La vue ne possède pas les données et toutes les modifications apportées à la vue affecteront le tableau d'origine et toutes les modifications apportées au tableau d'origine affecteront la vue.

### COPY

In [26]:
# Faites une copie, modifiez le tableau d'origine et affichez les deux tableaux:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr) 

[42  2  3  4  5]


In [27]:
print(x)

[1 2 3 4 5]


### VIEW

In [28]:
# Créez une vue, modifiez le tableau d'origine et affichez les deux tableaux:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr) 

[42  2  3  4  5]


In [29]:
print(x)

[42  2  3  4  5]


## Itération des Tableaux
Itérer signifie parcourir les éléments un par un.

Comme nous traitons des tableaux multidimensionnels dans numpy, nous pouvons le faire en utilisant la boucle for basique de python.

Si nous itérons sur un tableau 1D, il passera par chaque élément un par un.

In [30]:
import numpy as np

arr = np.array([1, 2, 3])

for x in arr:
  print(x)

1
2
3


### Tableau 2D
Dans un tableau 2D, il parcourra toutes les lignes.

In [31]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)

[1 2 3]
[4 5 6]


In [32]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
6


### Tableau 3D
Dans un tableau 3D, il passera par tous les tableaux 2D.

In [33]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [34]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  for y in x:
    for z in y:
      print(z)

1
2
3
4
5
6
7
8
9
10
11
12


### Itérer des tableaux avec nditer ()
La fonction **nditer()** est une fonction d'aide qui peut être utilisée à partir d'itérations très basiques à très avancées. Elle résout certains problèmes de base auxquels nous sommes confrontés dans l'itération.

#### Itération sur chaque élément scalaire
Dans les boucles **for** basiques, en parcourant chaque scalaire d'un tableau, nous devons utiliser **n** boucles **for**, ce qui peut être difficile à écrire pour les tableaux avec une dimensionnalité très élevée.

In [35]:
import numpy as np

arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


#### Itération avec une taille de pas différente
Nous pouvons utiliser le filtrage et suivi d'une itération.

In [37]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]):
  print(x)

1
3
5
7


## Joindre les tableaux NumPy
Joindre signifie placer le contenu de deux tableaux ou plus dans un seul tableau.

Nous passons une séquence de tableaux que nous voulons joindre à la fonction **concatenate()**, avec l'axe. Si l'axe n'est pas explicitement passé, il est considéré comme 0.

In [39]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [40]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


### Joindre des tableaux à l'aide de la fonction Stack
L'empilement est identique à la concaténation, la seule différence est que l'empilement est effectué le long d'un nouvel axe.

On peut concaténer deux tableaux 1D le long du deuxième axe ce qui aboutirait à les placer l'un sur l'autre, c'est-à-dire empilement.

Nous passons une séquence de tableaux que nous voulons joindre à la méthode **stack()** avec l'axe. Si l'axe n'est pas explicitement passé, il est considéré comme 0.

In [41]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


#### Empilement le long des lignes
NumPy fournit une fonction d'assistance: **hstack()** pour empiler le long des lignes.

In [43]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


#### Empilement le long des colonnes
NumPy fournit une fonction d'assistance: **vstack()** pour empiler le long des colonnes.

In [44]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


## Division des tableaux NumPy
Le fractionnement est une opération inverse de la jonction.

La jonction fusionne plusieurs tableaux en un seul et le fractionnement divise un tableau en plusieurs.

Nous utilisons **array_split()** pour diviser les tableaux, nous lui passons le tableau que nous voulons diviser et le nombre de divisions.

In [45]:
#Diviser le tableau en 3 parts : 

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [46]:
#Diviser le tableau en 4 parts : 
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


### Diviser en tableaux
La valeur de retour de la méthode **array_split()** est un tableau contenant chacun des fragments sous forme de tableau.

Si vous divisez un tableau en 3 tableaux, vous pouvez y accéder à partir du résultat comme n'importe quel élément du tableau:

In [48]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]


In [49]:
import numpy as np

arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [50]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


## Recherche de tableaux
Vous pouvez rechercher dans un tableau une certaine valeur et renvoyer les index qui obtiennent une correspondance.

Pour rechercher un tableau, utilisez la méthode **where()**.

In [69]:
# Rechercher les index dont la valeur est 4:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6]),)


In [70]:
# Trouver les index où les valeurs sont paires:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x)

(array([1, 3, 5, 7]),)


In [71]:
# Trouver les index où les valeurs sont impaires:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 1)

print(x)

(array([0, 2, 4, 6]),)


## Tri des tableaux
Le tri signifie placer les éléments dans une séquence ordonnée.

Une séquence ordonnée est toute séquence dont l'ordre correspond aux éléments, comme numérique ou alphabétique, croissant ou décroissant.

L'objet NumPy **ndarray** a une fonction appelée **sort()**, qui triera un tableau spécifié.

In [59]:
# Tri d'un tableau:

import numpy as np

arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]


In [60]:
# Tri d'un tableau par ordre alphabétique:

import numpy as np

arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

['apple' 'banana' 'cherry']


In [62]:
# Tri d'un tableau booléen:

import numpy as np

arr = np.array([True, False, True])

print(np.sort(arr))

[False  True  True]


In [64]:
# Tri d'un tableau 2D:

import numpy as np

arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


## Filtrage des tableaux
Extraire certains éléments d'un tableau existant et en créer un nouveau s'appelle le filtrage.

Dans NumPy, vous filtrez un tableau à l'aide d'une liste d'index booléenne.

Une liste d'index booléen est une liste de booléens correspondant aux index du tableau.

Si la valeur d'un index est True, cet élément est contenu dans le tableau filtré, si la valeur de cet index est False, cet élément est exclu du tableau filtré.

In [68]:
import numpy as np

arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr)

[41 43]


#### Création d'un tableau de filtres qui ne renverra que des valeurs supérieures à 42:

In [67]:
import numpy as np

arr = np.array([41, 42, 43, 44])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is higher than 42, set the value to True, otherwise False:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, False, True, True]
[43 44]


## Qu'est-ce qu'un nombre aléatoire?
Un nombre aléatoire ne signifie PAS un nombre différent à chaque fois. Aléatoire signifie quelque chose qui ne peut être prédit logiquement.

### Générer un nombre aléatoire
NumPy propose le module aléatoire pour travailler avec des nombres aléatoires.

#### Génération d'un nombre aléatoire entre 0 et 100

In [72]:
from numpy import random
x = random.randint(100)
print(x)

87


In [74]:
#### Génération d'un flottant aléatoire de 0 à 1:

In [75]:
from numpy import random
x = random.rand()
print(x)

0.6898518951744371


### Génération d'un tableau aléatoire
Dans NumPy, nous travaillons avec des tableaux, et vous pouvez utiliser les deux méthodes des exemples ci-dessus pour créer des tableaux aléatoires.

#### Entiers
La méthode **randint()** prend un paramètre de taille dans lequel vous pouvez spécifier la forme d'un tableau.

In [76]:
from numpy import random
x=random.randint(100, size=(5))
print(x)

[96 69 85  7 21]


#### Génération d'un tableau 2D avec 3 lignes, chaque ligne contenant 5 entiers aléatoires de 0 à 100:

In [77]:
from numpy import random
x = random.randint(100, size=(3, 5))
print(x)

[[34 61 15 39 27]
 [92 59 28 55 25]
 [37 33  3 45 54]]


#### Float
La méthode **rand()** vous permet également de spécifier la forme du tableau.

In [79]:
from numpy import random
x = random.rand(5)
print(x)

[0.20120451 0.24035606 0.24254606 0.89310305 0.23724314]


#### Génération d'un tableau 2D avec 3 lignes, chaque ligne contenant 5 nombres aléatoires:

In [81]:
from numpy import random
x = random.rand(3, 5)
print(x)

[[0.06880795 0.79231368 0.46214119 0.0302246  0.90161812]
 [0.10787222 0.67732166 0.50856425 0.06922125 0.92173267]
 [0.95152857 0.95209542 0.21555577 0.74591265 0.71400197]]


## Fonctions hyperboliques
* numpy.sinh(x) : sinus hyperbolique
* numpy.cosh(x) : cosinus hyperbolique
* numpy.tanh(x) : tangente hyperbolique
* numpy.arcsinh(x) : arcsinus hyperbolique
* numpy.arccosh(x) : arc cosinus hyperbolique
* numpy.arctanh(x) : arc tangente hyperbolique

## Fonctions trigonométriques
* numpy.sin(x) : sinus
* numpy.cos(x) : cosinus
* numpy.tan(x) : tangente
* numpy.arcsin(x) : arcsinus
* numpy.arccos(x) : arc cosinus
* numpy.arctan(x) : arc tangente

## Fonctions diverses
* numpy.sqrt(x) : racine carrée
* numpy.exp(x) : exponentielle
* numpy.log(x) : logarithme népérien
* numpy.abs(x) : valeur absolue
* numpy.sign(x) : signe

## Fonctions utiles pour les nombres complexes
* numpy.real(x) : partie réelle
* numpy.imag(x) : partie imaginaire
* numpy.abs(x) : module
* numpy.angle(x) : argument en radians
* numpy.conj(x) : complexe conjugué

## Arrondis
* numpy.around(x,n) : arrondi à n décimales
* numpy.trunc(x) : retourne la partie entière du nombre (le nombre est tronqué)
