## Graphe orienté pondéré

In [18]:
# Ajouter un sommet à l'ensemble des sommets et au graphe
def add_vertex(v):
    global graph
    global vertices_no
    global vertices
    if v in vertices:
        print("Sommet ", v, " existe déjà")
    else:
        vertices_no = vertices_no + 1
        vertices.append(v)
    if vertices_no > 1:
        for vertex in graph:
            vertex.append(0)
    temp = []
    for i in range(vertices_no):
        temp.append(0)
    graph.append(temp)

# Ajouter une arête entre les sommets v1 et v2 avec un poids d'arête e
def add_edge(v1, v2, e):
    global graph
    global vertices_no
    global vertices
    # Check if vertex v1 is a valid vertex
    if v1 not in vertices:
        print("Sommet ", v1, " n'existe pas.")
    # Check if vertex v1 is a valid vertex
    elif v2 not in vertices:
        print("Sommet ", v2, " n'existe pas.")
    else:
        index1 = vertices.index(v1)
        index2 = vertices.index(v2)
        graph[index1][index2] = e

# Dessin du graphe
def print_graph():
    global graph
    global vertices_no
    for i in range(vertices_no):
        for j in range(vertices_no):
            if graph[i][j] != 0:
                print(vertices[i], " -> ", vertices[j], \
                " Poids: ", graph[i][j])
            

# stocke les sommets du graphe
vertices = []
# stocke le nombre de sommets dans le graphe
vertices_no = 0
graph = []
# Ajouter des sommets au graphique

while True:
        try:
            add_vertex(input("saisir sommet : "))
            i = int(input("------Tapez votre choix------(0 pour exit)\n"))
            if i ==0:
                break   
        except Exception as e:
            print("e")

print('--------------------------------')        
 
# Ajoutez les arêtes entre les sommets en spécifiant
# le sommet from et to avec les poids des arêtes.

while True:
    try:
        add_edge((input("saisir sommet 1 : ")), (input("saisir sommet 2 : ")) , int(input("saisir poids : ")))
        k = int(input("------Tapez votre choix------(0 pour exit)\n"))
        if k ==0:
            break   
    except Exception as e:
        print("e") 

print('--------------------------------')        

print_graph()
print('--------------------------------')        
print("Matrice d'adjacence : ", graph)

saisir sommet : A
------Tapez votre choix------(0 pour exit)
1
saisir sommet : B
------Tapez votre choix------(0 pour exit)
1
saisir sommet : C
------Tapez votre choix------(0 pour exit)
0
--------------------------------
saisir sommet 1 : A
saisir sommet 2 : B
saisir poids : 12
------Tapez votre choix------(0 pour exit)
1
saisir sommet 1 : B
saisir sommet 2 : C
saisir poids : 23
------Tapez votre choix------(0 pour exit)
1
saisir sommet 1 : B
saisir sommet 2 : A
saisir poids : 4
------Tapez votre choix------(0 pour exit)
0
A  ->  B  Poids:  12
B  ->  A  Poids:  4
B  ->  C  Poids:  23
Matrice d'adjacence :  [[0, 12, 0], [4, 0, 23], [0, 0, 0]]


In [19]:
print(graph)

[[0, 12, 0], [4, 0, 23], [0, 0, 0]]


In [20]:
import numpy as np
A=np.array(graph)
print(A)

[[ 0 12  0]
 [ 4  0 23]
 [ 0  0  0]]


In [47]:
print("Nodes of graph: ")
print(vertices)

Nodes of graph: 
['A', 'B', 'C']
